[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "xactflow"
version = "0.1.0"
description = "Multi-file IP-XACT elaboration and semantic consistency checking on top of ipxact-compiler."
readme = "README.md"
license = "LGPL-3.0-only"
license-files = ["LICENSE"]
authors = [
    { name = "Maxime Travaillard"},
]
requires-python = ">=3.9"
dependencies = [
    "ipxact-compiler",
    "lxml",
]
keywords = [
    "IP-XACT", "IEEE 1685", "XML", "Compiler",
    "XactFlow",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]

[project.urls]
Repository = "https://github.com/IP-XACT/XactFlow"
Issues = "https://github.com/IP-XACT/XactFlow/issues"


[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
xactflow = "xactflow.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
xactflow = ["py.typed"]
